; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:portenta_h7_m4]
platform = ststm32
board = portenta_h7_m4
framework = arduino
upload_protocol = dfu
upload_port = COM3
build_flags = 
	-Wl,-Tm4/ldscripts/m4_bigmem.ld
	-Wl,-defsym,CM4_BINARY_START=0x08100000 
	; -DMBED_RAM_START=0x24004000                  ; our RAM_D1 origin
    ; -DMBED_RAM_SIZE=0x7C000                      ; 496 KB
    ; -DMBED_RAM1_START=0x38002000                 ; our RAM_D3 origin
    ; -DMBED_RAM1_SIZE=0x0E000                     ; 56 KB
lib_deps = 
	adafruit/Adafruit LSM6DS@^4.7.4
	adafruit/Adafruit Unified Sensor@^1.1.15
